name: plugins
version: '1.0-SNAPSHOT'
main: org.plugin.Main
api-version: '1.21'
commands:
  dudumtack :
    description: test
    usage: Oh no...
  돈 :
    description: 돈을 보여준다
    usage: 올바른 사용법 -> /돈 help